### ISSUE TITLE
Undeffine method replace_only

### ISSUE THREAD

**Issue by alanheli92** [sous-chefs/line-cookbook#231]
Hi there. i'm using the replace_or_add resource and i'm getting the bellow error.
NoMethodError[0m
 undefined method `replace_only' for Chef::Resource::ReplaceOrAdd[0m

Already check the cookbook metadata.rb have the depends to the line cookbook.
is ther a  usage doc apart from the resources documentation? 
Thanks

**Comment by MarkGibbons** [comment]
I'm out of town this week. I'll look at the issue Monday.

**Comment by MarkGibbons** [comment]
@alanheli92 <https://github.com/alanheli92> Could you add the
replace_or_add resource call from your recipe to the issue?

One of the better usage explanations is to look at the tests.
 test/fixtures/cookbooks/test/recipes/replace_or_add_replace_only.rb shows
two examples of using that option.

Thank you, Mark

**Comment by alanheli92** [comment]
Hi there. this the config for replace_or_add resource
```ruby
replace_or_add 'monitor' do
    path '/foo/bar/monitor.xml'
    pattern '<enabled>.*</enabled>'
    line "<enabled>#{monitor}</enabled>"
    replace_only true
    notifies :restart, 'service[monitor]', :delayed
end
```
Is pretty same to the examples that you have.
Linux flavor Amazon linux 2

**Comment by MarkGibbons** [comment]
Are you using the latest version of line?  What version of the chef client are you using?

**Comment by MarkGibbons** [comment]
Could you include the chef client log messages for this resource in this ticket?

**Comment by alanheli92** [comment]
the line version is 2.9.3 and i'm using chef solo

**Comment by MarkGibbons** [comment]
chef solo, but which version of the chef client?  I may need you to zip your cookbook or at least send a copy of the recipe. Whatever you are running into is sort of obscure.

**Comment by MarkGibbons** [comment]
I looked for a way to cause this problem and didn't see one.  I'm a little concerned about the characters at the end of the lines you pasted. Please see if your cookbook passes "cookstyle -a" cleanly.  If possible please send a stack trace from the error and the actual chef-client run of the resource.

**Comment by YAMLcase** [comment]
I'm getting similar error, also for line version `2.9.3`:
```
undefined method `replace_or_add' for cookbook: testcookbook, recipe: default :Chef::Recipe
```
chef-client 16.2.73.  I am using `depends 'line'` in my cookbook metadata.rb without specifying version

**Comment by MarkGibbons** [comment]
line is at version 4 something now. You might upgrade and see there is still a problem.
If you would like to pursue it please open a new issue and include a recipe that can be used to recreate the problem.

**Comment by YAMLcase** [comment]
This turned out to be a chef 16.2 [breaking change](https://discourse.chef.io/t/chef-infra-client-16-2-released/17284) solved by adding `include_recipe 'line'` to my default recipe

**Comment by MarkGibbons** [comment]
@YAMLcase Thank you for the follow up.
