### ISSUE TITLE
Unit testing line resources using Chefspec

### ISSUE THREAD

**Issue by kajalgupta26** [sous-chefs/line-cookbook#232]
Hi,

I am new to Chef and I am writing unit tests to test the resources using Chefspec. I have used line resources in my cookbook but I am not sure how to unit test them. Any example would be much helpful. I am using replace_or_add, filter_lines & append_if_no_line resources.

Thanks!

**Comment by MarkGibbons** [comment]
My opinion, chef spec unit tests for resources are not usually useful.  You can check that you have parameters specified but not much else.  In some sense unit tests for line resources would duplicate the tests we have set up in the line cookbook.  Tim Smith has some excellent chef conf talks about suggested test methods for cookbooks.

Opinion aside, if you really want a unit test for a line resource in a recipe. What would you like to verify with the test?

**Comment by kajalgupta26** [comment]
Hi, thanks for the prompt response. So, yes I know that chef unit tests is not much helpful as it validates just the parameters specified but I guess we still want to use it. Why? Because we have many cookbooks which when deployed will modify configurations of nearly million hosts. We want to be sure at each step from build to deployment to the chef runs. So we want to do unit test along with infra-test. 

This is a sample snippet from of the cookbooks which is replacing a line in a file:
```
  replace_or_add "replace-line-auth.*pam_unix.so.*" do
    path "#{etc_file}"
    pattern "auth.*pam_unix.so.*"
    line "auth        sufficient    pam_unix.so use_first_pass XXX nullok"
    replace_only true
  end
```

Like this there are various other small configurations that either need to be added or replaced. So we wanted to just unit test that exactly this is the line which is being inserted "auth        sufficient    pam_unix.so use_first_pass XXX nullok" and not this "auth        sufficient    pam_unix.so use_first_pass XXX nulok" coz its possible someone accidentally changes something and  we want to be able to catch it via unit tests. You can see it is just a way of validating everything in recipe is good.

If you think something else might be useful or if this doesn't makes sense please feel free to let me know!

**Comment by MarkGibbons** [comment]
Given a choice of testing a line resource with ChefSpec or with Inspec I would use inspec tests. You can see the difference in the internal line cookbook tests.  

https://docs.chef.io/workstation/chefspec/#context does have examples of testing resource property settings from cookbooks.  The examples showing how to test the template resource look like they would apply.  You could test for a resource in the cookbook and use the "with" operator to validate the property value specified in the recipe. 

If you haven't joined already I recommend the chefcommunity.slack.com slack as a place to ask questions and get help.  For this particular issue you will likely get non stop recommendations not to use ChefSpec. :-)   There are good reasons for that.

I'll close this ticket some time in the next week.  It's a bit out of scope for a line cookbook issue.  Good luck.

**Comment by MarkGibbons** [comment]
Gave a recommendation.  Good luck.
