### ISSUE TITLE
filter_lines does not detect existing lines if / is in stanza.

### ISSUE THREAD

**Issue by KenzoB73** [sous-chefs/line-cookbook#236]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

When using the stanza: feature of filter_lines, if my stanza has a / in it, the entry gets created as a second stanza, and will continue to create a duplicate stanza every time this recipe is run.

## :pancakes: Cookbook version

4.4.4

## :woman_cook:  Chef-Infra Version

17.10.3

## :tophat: Platform details

Ubuntu 18.04.6
## Steps To Reproduce

1. Create a recipe which uses the line cookbook.
2. Setup a stanza filter in that recipe.  

`filter_lines '/tmp/file.conf' do
  filters([
{stanza: ['test', { line1: 'true' }]},
{stanza: ["test2/test", { line2: 'False' }]}
])
end`
3. Execute that recipe.

## :police_car: Expected behavior

The new file should contain:

[test]
  line1 = true
[test2/test]
  line2 = False

If I run the recipe a second time, it contains this:

[test]
  line1 = true
[test2/test]
  line2 = False
[test2/test]
  line2 = False

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by MarkGibbons** [comment]
Thank you for the bug report.  I'll take a look.

**Comment by MarkGibbons** [comment]
Should be fixed by #237

**Comment by MarkGibbons** [comment]
"/" was not a supported character for stanza names and the code had a regex that tried but failed to detect invalid stanza names.

**Comment by MarkGibbons** [comment]
I'll try to figure out the issues with the build and get the fix merged this weekend.

**Comment by MarkGibbons** [comment]
The fix was merged
